apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: '1.21.4-bb.6'
appVersion: 9.12.15
kubeVersion: ">=1.21.x-0"
keywords:
  - Jira
  - Jira Software
  - Jira Server
  - Jira Data Center
  - Jira DC
  - Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Update appVersions for DC apps (#865)"
  bigbang.dev/applicationVersions: |
    - Jira: 9.12.14
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    The [upstream Jira helm chart changelog](https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/jira/Changelog.md) may help when reviewing this package.
  helm.sh/images: |
    - name: jira-node-lts
      image: registry1.dso.mil/ironbank/atlassian/jira-data-center/jira-node-lts:9.12.15
    - name: nfs-permission-fixer
      image: registry1.dso.mil/ironbank/redhat/ubi/ubi8-minimal:8.10
    - name: fluentd-kubernetes-daemonset
      condition: fluentd.enabled
      image: registry1.dso.mil/ironbank/opensource/fluentd/fluentd-kubernetes-daemonset:1.17.1
dependencies:
  - name: common
    version: 1.2.7
    repository: https://atlassian.github.io/data-center-helm-charts
  - name: gluon
    repository: oci://registry1.dso.mil/bigbang
    version: 0.5.11
