apiVersion: v2
name: jira
description: A chart for installing Jira Data Center on Kubernetes
type: application
version: 1.15.1-bb.4
appVersion: 9.10.0
kubeVersion: ">=1.21.x-0"
keywords:
- Jira
- Jira Software
- Jira Server
- Jira Data Center
- Jira DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/jira-software.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: changed
      description: Fix artifacthub annotations
  bigbang.dev/applicationVersions: |
    - Jira: 9.10.0
  helm.sh/images: |
    - name: jira-node
      image: registry1.dso.mil/ironbank/atlassian/jira-data-center/jira-node:9.10.0
    - name: nfs-permission-fixer
      image: registry1.dso.mil/ironbank/redhat/ubi/ubi8-minimal:8.8
    - name: fluentd-kubernetes-daemonset
      condition: fluentd.enabled
      image: registry1.dso.mil/ironbank/opensource/fluentd/fluentd-kubernetes-daemonset:1.16.2
  artifacthub.io/changes: |-
    - "Make startup probes optional (#646)"

dependencies:
  - name: common
    repository: https://atlassian.github.io/data-center-helm-charts
    version: 1.2.3
  - name: gluon
    repository: oci://registry1.dso.mil/bigbang
    version: 0.3.2
