apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira.fullname" . }}
  labels:
    {{- include "jira.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.jira.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.jira.service.type }}
  ports:
    - port: {{ .Values.jira.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.jira.ports.http2 }}
      targetPort: {{ .Values.jira.ports.http2 }}
      protocol: TCP
      name: http2
    - port: {{ .Values.jira.ports.ehcache }}
      targetPort: {{ .Values.jira.ports.ehcache }}
      protocol: TCP
      name: ehcache
    - port: {{ .Values.jira.ports.ehcacheobject }}
      targetPort: {{ .Values.jira.ports.ehcacheobject }}
      protocol: TCP
      name: ehcache-object
  selector:
    {{- include "jira.selectorLabels" . | nindent 4 }}
