apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira.fullname" . }}
  labels:
    {{- include "jira.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jira.service.type }}
  ports:
    - port: {{ .Values.jira.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http2
    - port: 40001
      targetPort: 40001
      protocol: TCP
      name: ehcache
    - port: 40011
      targetPort: 40011
      protocol: TCP
      name: ehcache-object
  selector:
    {{- include "jira.selectorLabels" . | nindent 4 }}
