{{- if .Values.volumes.sharedHome.efs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jira.fullname" . }}-shared-home-pv
  labels:
  {{- include "jira.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.volumes.sharedHome.persistentVolumeClaim.resources.requests.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  claimRef:
    name: {{ include "jira.fullname" . }}-shared-home
    namespace: {{ .Release.Namespace }}
  csi:
    driver: {{ .Values.volumes.sharedHome.driver }}
    volumeHandle: {{ .Values.volumes.sharedHome.efsid }}
  {{ end }}
