{{- if .Values.volumes.sharedHome.efs.persistentVolumeClaim.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-shared-home
  labels:
  {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  volumeName: {{ include "common.names.fullname" . }}-shared-home-pv
  accessModes:
  {{ range .Values.volumes.sharedHome.efs.persistentVolumeClaim.accessModes }}
    - {{ . }}
  {{- end }}
  {{- if .Values.volumes.sharedHome.efs.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.volumes.sharedHome.efs.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
  {{- with .Values.volumes.sharedHome.efs.persistentVolumeClaim.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
{{- else }}
  {{- if .Values.volumes.sharedHome.nfs.persistentVolumeClaim.create }}
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: {{ include "common.names.fullname" . }}-shared-home
    labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
  spec:
    volumeName: {{ include "common.names.fullname" . }}-shared-home-pv
    accessModes:
    {{ range .Values.volumes.sharedHome.nfs.persistentVolumeClaim.accessModes }}
      - {{ . }}
    {{- end }}
    {{- if .Values.volumes.sharedHome.nfs.persistentVolumeClaim.storageClassName }}
    storageClassName: {{ .Values.volumes.sharedHome.nfs.persistentVolumeClaim.storageClassName | quote }}
    {{- end }}
    {{- with .Values.volumes.sharedHome.nfs.persistentVolumeClaim.resources }}
    resources:
      {{- toYaml . | nindent 4 }}   
    {{- end }}
  {{- end }}
{{- end }}  
{{- end }}