{{- if .Values.upstream.database.type -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.upstream.database.credentials.secretName }}
type: Opaque
data:
  {{ .Values.upstream.database.credentials.usernameSecretKey }}: {{ tpl (.Values.upstream.database.user) . | b64enc }}
  {{ .Values.upstream.database.credentials.passwordSecretKey }}: {{ tpl (.Values.upstream.database.password) . | b64enc }}
{{- end -}}
