{{- $db := .Values.dbSecret | default dict -}}
{{- if and $db.enabled $db.secretName $db.databaseUser $db.databasePassword }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ $db.secretName }}
type: Opaque
data: 
  {{ default "username" $db.usernameSecretKey }}: {{ toString $db.databaseUser | b64enc }}
  {{ default "password" $db.passwordSecretKey }}: {{ toString $db.databasePassword | b64enc }}
{{- end }}
