{{- if .Values.upstream.volumes.sharedHome.efs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.names.fullname" . }}-shared-home-pv
  labels:
  {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.upstream.volumes.sharedHome.efs.persistentVolumeClaim.resources.requests.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.upstream.volumes.sharedHome.efs.persistentVolumeClaim.storageClassName | default "efs-sc" }}
  claimRef:
    name: {{ include "common.names.fullname" . }}-shared-home
    namespace: {{ .Release.Namespace }}
  csi:
    driver: {{ .Values.upstream.volumes.sharedHome.efs.driver }}
    volumeHandle: {{ .Values.upstream.volumes.sharedHome.efs.efsid }}
{{- else if .Values.upstream.volumes.sharedHome.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.names.fullname" . }}-shared-home-pv
  labels:
  {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.upstream.volumes.sharedHome.nfs.persistentVolumeClaim.resources.requests.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.upstream.volumes.sharedHome.nfs.persistentVolumeClaim.storageClassName }}
  claimRef:
    name: {{ include "common.names.fullname" . }}-shared-home
    namespace: {{ .Release.Namespace }}
  csi:
    server: {{ .Values.upstream.volumes.sharedHome.nfs.server }}
    path: {{ .Values.upstream.volumes.sharedHome.nfs.path }}
{{- end }}
