{{- if and (.Values.istio.enabled) (.Values.istio.jira.enabled) -}}
{{- $serviceName := include "common.names.fullname" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: jira
  {{- if .Values.istio.jira.labels }}
{{ toYaml .Values.istio.jira.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.jira.annotations }}
  annotations:
{{ toYaml .Values.istio.jira.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.jira.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.jira.hosts }}
    - {{ tpl . $ }}
  {{- end }}
  http:
  {{- if .Values.monitoring.exposeJmxMetrics }}
  - match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: jira-jmx.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.monitoring.jmxExporterPort }}
  {{- end }}
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ $serviceName}}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.jira.service.port }}
{{- end }}
